# Generated by Django 5.0.1 on 2024-07-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="added",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="published",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
